CREATE DATABASE DATABASENAME ;  
GRANT ALL ON DATABASENAME.* TO DBUSER@'localhost' IDENTIFIED BY 'DBPASSWORD';
GRANT ALL ON DATABASENAME.* TO DBUSER@'127.0.0.1' IDENTIFIED BY 'DBPASSWORD';
FLUSH PRIVILEGES;
EXIT
